### ISSUE TITLE
Consider exposing Argon2.no_user_verify

### ISSUE THREAD

**Issue by michaeljones** [lpil/antigone#1]
I came across this when browsing what I assume is some auto-generated user auth code in an Elixir project of mine. It has:

```
  @doc """
  Verifies the password.

  If there is no user or the user doesn't have a password, we call
  `Argon2.no_user_verify/0` to avoid timing attacks.
  """
  def valid_password?(%Doable.Accounts.User{password_hash: password_hash}, password)
      when is_binary(password_hash) and byte_size(password) > 0 do
    Argon2.verify_pass(password, password_hash)
  end

  def valid_password?(_, _) do
    Argon2.no_user_verify()
    false
  end
```
Which indicates the need for `no_user_verify` to be exposed. I'm happy to try to do that.

I also think that the README could emphasise the existence of the `verify` function as when I started to use this I tried to compute the hash of the incoming password and compare that against the database but that doesn't seem to be how things should be done.

**Comment by lpil** [comment]
Thank you

**Comment by michaeljones** [comment]
Created https://github.com/lpil/antigone/pull/2 to add it.
